### ISSUE TITLE
screen shot

### ISSUE THREAD

**Issue by pishguy** [Hannnes1/snapping_page_scroll#4]
is there any screen shot of this library?

**Comment by Hannnes1** [comment]
I can try to upload some images / gifs tomorrow.

**Comment by Hannnes1** [comment]
I have added a gif to the [readme](https://github.com/Gothenburg-Application-Studio/snapping_page_scroll/blob/master/README.md); hope that helps you!

**Comment by Hannnes1** [comment]
I'm going to assume this has been solved since I haven't heard back from you.
